version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    env_file:
      - "./.env"

  postgres:
    image: postgres:11.2-alpine
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data/
    env_file:
      - database.env

  adminer:
      image: adminer
      restart: always
      ports:
        - 8001:8080

volumes:
  database-data:
